# Generated by Django 4.2.3 on 2023-10-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
    ]
