# Generated by Django 4.2.3 on 2023-10-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0005_remove_user_category_vendor_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='phno',
            field=models.CharField(default='', max_length=12),
        ),
    ]
